src/Entity/QuenyLog.php
<?php

namespace App\Entity;

use App\Repository\QuenyLogRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuenyLogRepository::class)
 */
class QuenyLog
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $quent;

    /**
     * @ORM\Column(type="text")
     */
    private $answer;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_time;

    /**
     * @ORM\Column(type="integer")
     */
    private $responce_code;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuent(): ?string
    {
        return $this->quent;
    }

    public function setQuent(string $quent): self
    {
        $this->quent = $quent;

        return $this;
    }

    public function getAnswer(): ?string
    {
        return $this->answer;
    }

    public function setAnswer(string $answer): self
    {
        $this->answer = $answer;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->date_time;
    }

    public function setDateTime(\DateTimeInterface $date_time): self
    {
        $this->date_time = $date_time;

        return $this;
    }

    public function getResponceCode(): ?int
    {
        return $this->responce_code;
    }

    public function setResponceCode(int $responce_code): self
    {
        $this->responce_code = $responce_code;

        return $this;
    }
}

src/Entity/TaskLog.php
<?php

namespace App\Entity;

use App\Repository\TaskLogRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TaskLogRepository::class)
 */
class TaskLog
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $task_code;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $startTime;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $requestSize;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $records;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $recordsProcessed;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $recordsError;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $schedule;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $end_time;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duration;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTaskCode(): ?string
    {
        return $this->task_code;
    }

    public function setTaskCode(?string $task_code): self
    {
        $this->task_code = $task_code;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->startTime;
    }

    public function setStartTime(?\DateTimeInterface $startTime): self
    {
        $this->startTime = $startTime;

        return $this;
    }

    public function getRequestSize(): ?int
    {
        return $this->requestSize;
    }

    public function setRequestSize(?int $requestSize): self
    {
        $this->requestSize = $requestSize;

        return $this;
    }

    public function getRecords(): ?int
    {
        return $this->records;
    }

    public function setRecords(?int $records): self
    {
        $this->records = $records;

        return $this;
    }

    public function getRecordsProcessed(): ?int
    {
        return $this->recordsProcessed;
    }

    public function setRecordsProcessed(?int $recordsProcessed): self
    {
        $this->recordsProcessed = $recordsProcessed;

        return $this;
    }

    public function getRecordsError(): ?int
    {
        return $this->recordsError;
    }

    public function setRecordsError(?int $recordsError): self
    {
        $this->recordsError = $recordsError;

        return $this;
    }

    public function getSchedule(): ?string
    {
        return $this->schedule;
    }

    public function setSchedule(?string $schedule): self
    {
        $this->schedule = $schedule;

        return $this;
    }

    public function getEndTime(): ?\DateTimeInterface
    {
        return $this->end_time;
    }

    public function setEndTime(?\DateTimeInterface $end_time): self
    {
        $this->end_time = $end_time;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }
}

templates/alt/cronResult_alt.html.twig
<style>
    body{
        background-color: lightgrey;
    }
</style>
<div class="table-responsive">

    <a href="/command-scheduler/detail/new">click here to Create NEW CRON</a>
    </br>
    <a href="/command-scheduler/list">click here to open CRON menu</a>
    </br>
    </br>
    <a href="/manualformalt">click here to start manual query</a>
    </br>
    <a href="/marketformalt">click here to start alternative manual query(with pre-set)</a>
    </br>
    </br>
    <a href="/showmarketext">click here to view market products</a>
    </br>

    {% if is_granted('ROLE_ADMIN') %}
        </br>
        <a href="/user_formalt">click here to edit user(ADMIN ONLY!)</a>
        </br>
        <a href="/editsupplieralt">click here to edit supplier data((ADMIN ONLY!))</a>
    {% endif %}
    </br>
    </br>
    <a href="/login ">click here to re-LOGIN/LOGOUT</a>
    </br></br>
    Last RUN logs:
    <table class="table table-condensed" border="1" cellpadding="10">
        <tr>
            <th><h4> ID</h4></th>
            <th><h4> task_code </h4></th>
            <th><h4> record_size </h4></th>
            <th><h4> records </h4></th>
            <th><h4> records_proceed </h4></th>
            <th><h4> records_error </h4></th>
            <th><h4> start_time </h4></th>
            <th><h4> end_time </h4></th>
            <th><h4> duration(uc) </h4></th>
            <th><h4> status </h4></th>
        </tr>

        {% for task_log in task_log %}
            <tr>
                <td> {{ task_log.ID }}                 </td>
                <td> {{ task_log.taskCode }}           </td>
                <td> {{ task_log.requestSize }}           </td>
                <td> {{ task_log.records }}           </td>
                <td> {{ task_log.recordsProcessed }}           </td>
                <td> {{ task_log.recordsError }}           </td>
                <td> {{ task_log.startTime |date("m/d/Y H/i/s") }} </td>
                <td> {{ task_log.endTime |date("m/d/Y H/i/s") }} </td>
                <td> {{ task_log.duration }}           </td>
                <td> {{ task_log.status }}           </td>
            </tr>
        {% endfor %}
    </table>
{#    </br>#}
{#    Last CustomCommand logs:#}
{#    <table class="table table-condensed" border="1" cellpadding="10">#}
{#        <tr>#}
{#            <th><h4> ID</h4></th>#}
{#            <th><h4> queny </h4></th>#}
{#            <th><h4> answer </h4></th>#}
{#            <th><h4> last run </h4></th>#}
{#            <th><h4> response </h4></th>#}
{#        </tr>#}
{#        {% for queny_log in queny_log %}#}
{#            <tr>#}
{#                <td> {{ queny_log.ID }}                 </td>#}
{#                <td> {{ queny_log.quent}}                 </td>#}
{#                <td> {{ queny_log.answer}}                 </td>#}
{#                <td> {{ queny_log.dateTime | date("m/d/Y H/i/s") }}    </td>#}
{#                <td> {{ queny_log.responceCode}}                 </td>#}
{#            </tr>#}
{#        {% endfor %}#}
{#    </table>#}
</div>

templates/alt/cronform_alt.html.twig
{% extends "default/default.html.twig" %}

{% block title %}
    {{ 'Manual request'|trans }}
{% endblock title %}

{% block content %}
    <style>

        .api_request {
            width: 95%;
            margin: 0.5%;
            margin-left: 1.2%;
        }

        .api_priority {
            width: 15%;
            margin: 0.5%;
            margin-left: 0.8%;
        }

        .api_retry{
            width: 15%;
            margin: 0.5%;
            margin-left: 1.5%;
        }

        .api_schedule{
            width: 15%;
            margin: 0.5%;
            margin-left: 0.3%;
        }

        .api_result {
            color: red;
            font-size: 16pt;
            width: 15%;
            margin: 1%;
        }

        .api_requesttype{
            margin-left: 3.5%;
            margin-bottom: 2%;
        }

        .api_supplier {
            width: 15%;
            margin: 0.5%;
            margin-left: 0.52%;
        }

        .api_type {
            width: 15%;
            margin: 0.5%;
            margin-left: 1%;
        }

        .jobs {
            width: 15%;
            margin: 0.5%;
            margin-left: 1.8%;
        }

        .tasks{
            width: 15%;
            margin: 0.5%;
            margin-left: 1.3%;
        }

        .task{
            width: 15%;
            margin: 10px;
            margin-left: 1.8%;
        }

        .submit{
            width: 10%;
        }

    </style>


    {% set styleConfiguration = {'class': 'form-control'} %}
    <div class="col-lg-6 col-sm-12">
        {{ form_start( form ) }}
        {{ form_end( form ) }}

        {{ form_start( form_t ) }}
        {{ form_end( form_t) }}

        {{ form_start( form2 ) }}
        {{ form_end( form2) }}

        {{ form_start( form3 ) }}
        {{ form_end( form3) }}

        {{ form_start( form4 ) }}
        {{ form_end( form4) }}

    </div>
    </br>
    <a href="/login ">click here to re-LOGIN/LOGOUT</a>
    </br>
    </br>
    <a href="/showcron ">click here for return to main menu</a>

{% endblock content %}

templates/alt/editsupplier_alt.html.twig
<style>
    body {

    }

    .submit
    {
        width: 10%;
    }

    .sup_label{
        width: 20%;
        margin: 0.5%;
        margin-left: 2%;
    }

    .sup_choose{
        width: 20%;
        margin: 0.5%;
        margin-left: 1%;
    }

    .sup_login{
        width: 20%;
        margin: 0.5%;
        margin-left: 2.2%;
    }

    .sup_password{
        width: 20%;
        margin: 0.5%;
        margin-left: 1%;
    }

    .sup_grant{
        width: 20%;
        margin: 0.5%;
        margin-left: 0.6%;
    }

    .api_result {
        color: red;
        font-size: 18pt;
        width: 20%;
        margin: 1%;
        margin-left: 2.5%;
    }

    .sup_delay{
        width: 20%;
        margin: 0.5%;
        margin-left: 2.2%;
    }

    .sup_url{
        width: 20%;
        margin: 0.5%;
        margin-left: 1.6%;
    }

    .sup_token{
        width: 20%;
        margin: 0.5%;
        margin-left: 0.8%;
    }

    .sup_oath{
        width: 20%;
        margin: 0.5%;
        margin-left: 0.15%;
    }

    .sup_new{
    }

</style>

<p>
    <span style="font-size: 250%; color:red ;">
        WARNING! BE CAREFUL!
    </span>
</p>

{{ form_start(form2) }}
{{ form_end(form2) }}
{{ form_start(form) }}
{{ form_end(form) }}
{{ form_start(form3) }}
{{ form_end(form3) }}
{{ form_start(form4) }}
{{ form_end(form4) }}
</br>
<a href="/login ">click here to re-LOGIN/LOGOUT</a>
</br>
<a href="/showcronalt ">click here for return to mainmenu</a>

templates/alt/manual_alt.html.twig
{% extends "default/default.html.twig" %}

{% block title %}
    {{ 'Manual request'|trans }}
{% endblock title %}

{% block content %}

    <style>

        .api_answer {
            height: 400px !important;
            width: 195% ;
            font-size: 14pt;
        }

        .api_body {
            height: 200px;
            width: 100%;
            font-size: 14pt;
        }

        .api_request {
            width: 195%;
            margin: 0.5%;
            margin-left: 0.1%;
        }

        .api_type {
            width: 99.5%;
            margin-left: 0.1%;
        }

        .api_url {
            margin-left: 1.7%;
            width: 40%;
        }

        .api_result {
            color: red;
            font-size: 18pt;
            width: 99%;
            margin-left: 0.5%;
        }

        .api_supplier{
            margin: 1%;
            margin-left: 1.58%;
            width: 5%;
        }

        .submit
        {
            width: 10%;
        }

    </style>

    {% set styleConfiguration = {'class': 'form-control'} %}
    <div class="col-lg-6 col-sm-12">
        {{ form_start( form ) }}

        {# Form's fields #}
        {{ form_row( form.Request ) }}
        {{ form_row( form.supplier, {'attr': styleConfiguration } ) }}
        {{ form_row( form.TYPE) }}
        {{ form_row( form.body) }}


        {# Form's actions #}
        <div class="row">
        {#    <a href="{{ path('showcronalt') }}" class="btn btn-default btn-lg" role="button">Back to menu</a>#}

            {{ form_widget( form.save, {'attr': {'class': 'btn btn-success btn-lg pull-right'} } ) }}
        </div>
        {{ form_end( form ) }}

        {{ form_start( form3 ) }}
        {{ form_end( form3) }}
        <a href="/login ">click here to re-LOGIN/LOGOUT</a>
        </br>
         <a href="/showcronalt ">click here for return to mainmenu</a>
    </div>

{% endblock content %}

templates/alt/marketProduct_alt.html.twig
<style>
    body{
        background-color: lightgrey;
    }
</style>
<div class="table-responsive">
    </br>
    <a href="/showcronalt ">click here for return to mainmenu</a>
    </br>
    </br>
    Market products:
    <table class="table table-condensed" border="1" cellpadding="10">
        <tr>
            <th><h4> ID</h4></th>
            <th><h4> SKU </h4></th>
            <th><h4> name </h4></th>
            <th><h4> search_name </h4></th>
            <th><h4> price </h4></th>
            <th><h4> stock </h4></th>
            <th><h4> edit time </h4></th>
            <th><h4> RTL size </h4></th>
            <th><h4> category </h4></th>
        </tr>

        {% for product in product
            | sort((a, b) => a.sku <=> b.sku)
        %}
            <tr>
                <td> {{ product.id }}                 </td>
                <td> {{ product.sku }}           </td>
                <td> {{ product.name }}           </td>
                <td> {{ product.nameSearch }}           </td>
                <td> {{ product.chnPriceRetail }}           </td>
                <td> {{ product.btchStock }}           </td>
                <td> {{ product.editTime }}           </td>
                <td> {{ product.rtlSizeCode }}           </td>
                <td> {{ product.category }}           </td>
            </tr>
        {% endfor %}
    </table>
</div>

templates/alt/marketProduct_alt_ext.html.twig
<head>
    <link rel="stylesheet" type="text/css"
          href="https://cdn.datatables.net/v/dt/jq-3.2.1/dt-1.10.16/datatables.min.css"/>
</head>

<style>
    .text-center {
        align-items: center;
    }
    .dataTables_wrapper {
        margin: 0 auto;
        width: 75%;
    }
</style>
<a href="/showcronalt ">click here for return to mainmenu</a>
</br>
<body>
<div id="products">Loadi...</div>

{# {% block javascripts_footer %} #}
{# <script src="{{ asset('vendor/jquery/jquery.min.js') }}"> #}
{# {% endblock %} #}
{# <script src="jquery.js"></script> #}
{% block javascripts %}
    <script src="https://code.jquery.com/jquery.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-3.2.1/dt-1.10.16/datatables.min.js"></script>
    <script src="{{ asset('bundles/datatables/js/datatables.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('#products').initDataTables({{ datatable_settings(datatable) }},
                {searching: true, dom: '<"wrapper"flipt>'});
        });
    </script>
{% endblock %}
</body>

templates/alt/marketQuery_alt.html.twig
{% extends "default/default.html.twig" %}

{% block title %}
    {{ 'Manual request'|trans }}
{% endblock title %}

{% block content %}
<style>
    .api_answer {

        height: 400px !important;
        width: 195% ;
        font-size: 14pt;
    }

    .api_body {
        height: 200px;
        width: 100%;
        font-size: 14pt;
    }

    .api_request {
        width: 195%;
        margin: 0.5%;
        margin-left: 0.1%;
    }

    .api_type {
        margin: 1.5%;
        width: 55%;
        margin-left: 4%;
    }

    .api_url {
        margin-left: 1.7%;
        width: 40%;
    }

    .api_result {
        color: red;
        font-size: 18pt;
        width: 195%;
        margin-left: 0.5%;
    }

    .sup_choose{
        margin: 1%;
        margin-left: 1.58%;
        width: 55%;
    }

    .query_choose{
        margin: 1%;
        margin-left: 4.58%;
        width: 55%;
    }

    .api_label
    {
        margin: 1%;
        width: 55%;
        margin-left: 5%;
    }

    .submit
    {

    }
</style>

    {% set styleConfiguration = {'class': 'form-control'} %}

    <div class="col-lg-6 col-sm-12">
        {{ form_start( form ) }}
        {# Form's fields #}
        {{ form_row( form.supplier , {'attr': styleConfiguration }) }}
        {{ form_row( form.Request ) }}
        {{ form_row( form.TYPE, {'attr': styleConfiguration }) }}
        {# Form's actions #}
        <div class="row">
            {{ form_widget( form.send, {'attr': {'class': 'btn btn-success btn-lg pull-left'} } ) }}
        </div>
        </br>
        {{ form_row( form.label, {'attr': styleConfiguration }) }}
        <div class="row">
            {{ form_widget( form.save, {'attr': {'class': 'btn btn-success btn-lg pull-left'} } ) }}
        </div>
        {{ form_end( form ) }}
        </br>

        {{ form_start( form2 ) }}
        {{ form_row( form2.query , {'attr': styleConfiguration }) }}
        <div class="row">
            {{ form_widget( form2.run, {'attr': {'class': 'btn btn-success btn-lg pull-left'} } ) }}
        </div>

        <div class="row">
            {{ form_widget( form2.delete, {'attr': {'class': 'btn btn-default btn-lg'} } ) }}
        </div>
        {{ form_end( form2) }}
        </br>
        {{ form_start( form3 ) }}
        {{ form_end( form3) }}
        <a href="/login ">click here to re-LOGIN/LOGOUT</a>
        </br>
        <a href="/showcronalt ">click here for return to mainmenu</a>
    </div>

{% endblock content %}

templates/alt/userform_alt.html.twig
<style>
    .submit
    {
        width: 10%;
    }

   .user_list{
       margin: 0.5%;
       margin-left: 2.58%;
       width: 20%;
   }

   .user_password{
       margin: 0.5%;
       margin-left: 1.58%;
       width: 20%;
   }

    .user_email{
        margin: 0.5%;
        margin-left: 2.7%;
        width: 20%;
    }

   .api_result {
       color: red;
       font-size: 18pt;
       width: 20%;
       margin: 1%;
       margin-left: 2.5%;
   }
</style>

<p>
    <span style="font-size: 250%; color:red ;">
        WARNING! BE CAREFUL!
    </span>
</p>

{{ form_start(form) }}
{{ form_end(form) }}
{{ form_start(form2) }}
{{ form_end(form2) }}
{{ form_start(form3) }}
{{ form_end(form3) }}
{{ form_start(form4) }}
{{ form_end(form4) }}
</br>
<a href="/login ">click here to re-LOGIN/LOGOUT</a>
</br>
<a href="/showcronalt ">click here for return to mainmenu</a>